export const HIKES = [
  {
    id: 'corner_store',
    name: 'Walk to the Corner Store',
    description: '0.3 miles. Flip flops are fine.',
    distanceLabel: '0.3 mi',
    steps: 600,
    funFact: 'You could have driven there in 90 seconds.',
  },
  {
    id: 'around_the_block',
    name: 'Lap Around the Block',
    description: 'One loop. Classic.',
    distanceLabel: '1 mi',
    steps: 2000,
    funFact: 'Most people walk about 2,000 steps per mile. You just did it with your fingers.',
  },
  {
    id: 'walk_the_dog',
    name: 'Walk the Dog',
    description: 'Three miles. The dog stopped to smell everything.',
    distanceLabel: '3 mi',
    steps: 6000,
    funFact: 'Your dog smelled 47 things, investigated 12 of them, and was unsatisfied with all of them.',
  },
  {
    id: 'casual_5k',
    name: 'A Casual 5K',
    description: '3.1 miles of mild exertion.',
    distanceLabel: '5 km',
    steps: 10000,
    funFact: 'The word "casual" is doing a lot of heavy lifting here.',
  },
  {
    id: 'half_marathon',
    name: 'Half Marathon',
    description: '13.1 miles. You signed up for this.',
    distanceLabel: '13.1 mi',
    steps: 42000,
    funFact: 'Half of a full marathon, but also twice as far as a half-marathon sounds.',
  },
  {
    id: 'appalachian_trail',
    name: 'Appalachian Trail',
    description: '2,190 miles from Georgia to Maine.',
    distanceLabel: '2,190 mi',
    steps: 5000000,
    funFact: 'Most thru-hikers take 5–7 months. You are attempting this with your thumbs.',
  },
  {
    id: 'walk_to_the_moon',
    name: 'Walk to the Moon',
    description: '238,855 miles. Bring snacks.',
    distanceLabel: '238,855 mi',
    steps: 380000000,
    funFact: 'Only 12 humans have ever been to the moon. None of them walked there.',
  },
];
